services:
  - type: web
    name: uri-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app --workers 1 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RENDER_DB_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_FILE
        value: service_account.json
